### ISSUE TITLE
Blank browser running on Linux

### ISSUE THREAD

**Issue by jat255** [BobStrogg/teslacam-browser#1]
Cool project!

I just tried running this on Linux with `npm install` and `npm start` (I'm not overly familiar with Electron, but I think that's what's required).

I get the following, when I select either the root USB mount directory, the TeslaCam directory, or the `SavedClips` directory:

![image](https://user-images.githubusercontent.com/1278301/56542711-4c5bb600-653d-11e9-9c81-26a1a0fe26e5.png)

And nothing in the console either:

![image](https://user-images.githubusercontent.com/1278301/56542757-70b79280-653d-11e9-9a55-262cee1a8fc5.png)

Any ideas what I might be doing wrong?

**Comment by jat255** [comment]
Oh actually it's working now... Not sure what I did different!

I selected the `SavedClips` folder

![image](https://user-images.githubusercontent.com/1278301/56543609-ede40700-653f-11e9-8e68-3d22c7d88c90.png)

**Comment by BobStrogg** [comment]
You got it working better than I did!  I've been wrestling with deploying prebuilt Electron packages, but not quite figured it all out yet.

Definitely needs plenty of refinement :)

**Comment by BobStrogg** [comment]
What maybe happened first time is you might've closed the folder selection popup at the start.  Currently it doesn't have an "Open" button to bring it back, and the only way to fix it is to close & reopen the window.
