### ISSUE TITLE
None of the buttons work

### ISSUE THREAD

**Issue by schlack** [BobStrogg/teslacam-browser#10]
When launching the app via the index.html file, none of the buttons are clickable in Safari or Chrome.

**Comment by BobStrogg** [comment]
It’s intended to run as a stand-alone Electron app (which uses node.js as a local web server).  The “Releases” page has ready-to-run packages for macOS, Windows and Linux 👍🏻

**Comment by schlack** [comment]
Ahh, my bad. Feeling slight dumb. ;)

Thanks for the reply. I’ll grab a release version.

**Comment by BobStrogg** [comment]
No worries!  GitHub still intimidates me; I only know what a few of the buttons do 👍🏻 (I only discovered the Releases tab a couple of weeks ago 😳)
