### ISSUE TITLE
Feature Request: Mobile port

### ISSUE THREAD

**Issue by gianmd** [BobStrogg/teslacam-browser#11]
I notice that the app is made with Web tchnologies, is possible to port it to an android app to read files from the sd card?

**Comment by BobStrogg** [comment]
It’s certainly possible.  It’s basically just node.js with an embedded Chrome browser, so anything that can provide node.js + a browser + local file access would work...

**Comment by mitchcapper** [comment]
https://blog.usejournal.com/how-to-build-android-apps-with-node-js-using-android-js-2aa4643be87b may be a good starting point if anyone wants to do a PR for this.  Keep in mind you could host on a remote box and then access remotely if you are simply looking to review from your phone.
