### ISSUE TITLE
no video playback

### ISSUE THREAD

**Issue by mikehaney24** [BobStrogg/teslacam-browser#13]
Hello! Seems like a great project, but I'm having difficulty getting any video to play.

Example: https://imgur.com/a/uoT3sfP

Running it using `npm start` isn't showing any particular useful output, just an objc runtime warning.

```
$: npm start

> teslacam-browser@0.0.88 start /Users/mhaney/Development/teslacam-browser
> electron .

Skip checkForUpdatesAndNotify because application is not packed
GVA info: Successfully connected to the Intel plugin, offline Gen95
objc[95275]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8ab213c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x112fcbf50). One of the two will be used. Which one is undefined.
```

**Comment by BobStrogg** [comment]
Interesting...  When the app is running, do any errors show up in the Console window?

Instructions if needed...

1. Open Developer Tools (View -> Toggle Developer Tools)
2. Select the "Console" tab
3. Are any errors shown? (they'll probably appear in red text)

**Comment by mikehaney24** [comment]
Yeah, there are some errors: https://imgur.com/a/xEUmSMD

Clicking play the first time gives `Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

Clicking play a second time gives
```
Uncaught (in promise) DOMException: The element has no supported sources.
videos.forEach.v @ /Users/mhaney/Development/teslacam-browser/renderer-helpers.js:68
playPause.addEventListener @ /Users/mhaney/Development/teslacam-browser/renderer-helpers.js:66
```

**Comment by BobStrogg** [comment]
Looking into this; thanks for letting me know!

**Comment by BobStrogg** [comment]
Are you on hardware 2.5 or 3?  Wondering if there’s been a codec change since HW3...

**Comment by mikehaney24** [comment]
HW3

**Comment by BobStrogg** [comment]
A pattern is emerging (similar issue with another HW3 user).  Will debug and see what’s going on... 🤔

**Comment by BobStrogg** [comment]
Added a new issue for this: #15

**Comment by mitchcapper** [comment]
Closing for #15 it has some possible solutions as well.
