### ISSUE TITLE
Videos Not in Chronological Order

### ISSUE THREAD

**Issue by tapr00t** [BobStrogg/teslacam-browser#14]
In versions .87 through .89 the videos in the list for a given event do not show up in chronological order.
![image](https://user-images.githubusercontent.com/3802245/57660837-6aee2380-75b6-11e9-839d-1c162db7486c.png)

**Comment by mitchcapper** [comment]
@tapr00t are you still seeing this issue with the current version?

**Comment by tapr00t** [comment]
yeah I still have the problem, videos won't play.  I tried installing the Microsoft HEVC codec, but I don't think chrome uses it (which I'm guessing your app is using to render).  The only way I can view them is if I open the files directly with a video player, or this site - but only with edge browser after installing that Microsoft codec:
https://sentrycam.appspot.com/

**Comment by mitchcapper** [comment]
Closing due to non-response please feel free to re-open if problem still exists.
