### ISSUE TITLE
0.0.9 Bottom view combines two minutes

### ISSUE THREAD

**Issue by aseniah** [BobStrogg/teslacam-browser#17]
This particular sentry event had 33 files, or just over 10 minutes of video. The last/bottom frame combined the 10th minute with the shorter 11th minute set of videos.
![Screen Shot 2019-05-24 at 3 09 03 PM](https://user-images.githubusercontent.com/4031128/58359114-b87c5300-7e36-11e9-8cb9-1ae8cc791678.png)

**Comment by aseniah** [comment]
In this case, It looks like the last 6 videos received the same file timestamp. It looks like your code is grouping by file date (line 195 of render.js) which is probably why all 6 ended up in the same frame.
![Screen Shot 2019-05-24 at 3 30 57 PM](https://user-images.githubusercontent.com/4031128/58359642-4f4a0f00-7e39-11e9-9091-63ed08174571.png)

**Comment by aseniah** [comment]
Ok, I'm wrong. Your code is definitely parsing the date from time file name, but it looks like the seconds are being discarded (line 187 of render.js).
I hope this is helpful? Happy to stop "being helpful". :)

**Comment by BobStrogg** [comment]
This is awesome feedback, thank you!  Yep this has been a buggy release, but will fix it this weekend 👍🏻

**Comment by BobStrogg** [comment]
Also I’ve not had chance to push the latest code yet, although as a workaround the latest source should be available as a zip on the release page.

**Comment by aseniah** [comment]
Fixed in 0.0.91. Thanks!
