### ISSUE TITLE
0.0.9 Scrub bar doesn't move when video plays

### ISSUE THREAD

**Issue by aseniah** [BobStrogg/teslacam-browser#18]
I'm noticing that the video scrub bar isn't moving while the video plays. I can use it to jump to any point in time, but it does not travel on its own.

**Comment by BobStrogg** [comment]
Does this happen every time, and is it happening directly in the app or after clicking the "Browse" button? (to open in external browser).

**Comment by aseniah** [comment]
Directly in the app, but this seems to be working fine in 0.0.91. Maybe it was just a fluke. I'll close the issue and report if I see it again with more details.
