### ISSUE TITLE
Feature Request: Expand/Collapse All

### ISSUE THREAD

**Issue by aseniah** [BobStrogg/teslacam-browser#19]
Generally with a Sentry event, the significant videos are the last couple of minutes. It would be nice to go back to a full view of all of the videos to get a general sense of what is occurring during the full 10 minutes without having to expand each one manually.

**Comment by BobStrogg** [comment]
I agree.  An earlier version did exactly that (actually it expanded on scroll).  I didn’t add it yet to the new Vue.js-based rendering, but was also concerned about how Safari seemed to struggle with more than a few videos. (when using the Browse button).

I’ll look into adding expand-on-scroll back, but also had another idea that might be worth trying...  It might work ok to hide / show consecutive videos as you move the slider or play through them (essentially it’d look like a single 10 minute video, probably with a larger slider with minute markers on it).  Would probably make both viewing options available.

**Comment by aseniah** [comment]
I like that idea! If I’m understanding this correctly, there would only be three videos shown at any point in time? If so, maybe the two side cameras could be moved below the center cam (kind of a triangle shape) to take more advantage of the screen real estate?

**Comment by BobStrogg** [comment]
Yep that’s what I’m thinking 👍🏻

Working on grouping consecutive clips into groups, which should be able to feed into this...

**Comment by aseniah** [comment]
I'm really liking the way the Combine Clips feature turned out. I think that is actually better than the Expand/Collapse All feature I was requesting. I'm going to close this issue. Thanks!
