### ISSUE TITLE
Cached missing last directory causes issues.

### ISSUE THREAD

**Issue by Breachfront** [BobStrogg/teslacam-browser#24]
If the cached last directory read is missing, the application throws errors.  Screenshot enclosed.
![image](https://user-images.githubusercontent.com/33228656/58705364-fb7d7f80-837c-11e9-8bfb-4d35ac498d1e.png)

**Comment by nathan-owen** [comment]
Can you try and pull the latest update? This has been fixed in the latest update/commit

**Comment by Breachfront** [comment]
Tested this with 0.0942, tried reverting to 0.0.91, both have the issue.

**Comment by Breachfront** [comment]
Also, could the rsync work in descending order?  Had an alarm last night, but it's transferring to the CIFS mount the earliest footage from days ago.

**Comment by nathan-owen** [comment]
It looks like they just merged the latest commit which fixes this issue and pushed a new release version. Would you mind trying that out?

**Comment by Breachfront** [comment]
Will do, I'll test it out this afternoon and let you know.  Thanks for the quick fix!

________________________________

**Comment by nathan-owen** [comment]
Sure thing! I actually ran across this issue a couple of days ago and wrote the fix, that's why I was l sure that the fix was available haha! I only tested on Windows, but theoretically it should work on all platforms

**Comment by Breachfront** [comment]
Will do, I'll test it out this afternoon and let you know.  Thanks for the quick fix!

**Comment by Breachfront** [comment]
Nice.  I might start contributing to this repo, I've got some ideas that would improve the experience.  I find it takes a while to manually skim through the videos for a couple seconds of motion, which is usually a false positive (ex: car driving by in the distance).  I'm thinking of some ways to condense the footage to only display significant motion, as a preview.

**Comment by BobStrogg** [comment]
All help appreciated 👍🏻  Yep for 0.0.942 I’d forgotten to pull the latest (with nathan-owen’s fix) before publishing.  0.0.943 should fix that.

**Comment by Breachfront** [comment]
Confirmed that the issue is now resolved.  Also, it appears that a ghost or possibly thunder set off my Sentry Mode alarm last night.  Thanks for the fix, you're awesome!
