### ISSUE TITLE
After delete it is changing the selected date

### ISSUE THREAD

**Issue by fmonera** [BobStrogg/teslacam-browser#26]
When I am watching the videos inside a date and delete one of them, the UI changes the date selected to today, so I have to go back in the calendar to de specific date I was reviewing. 

That makes very uncomfortable to watch and delete old / irrelevant videos.

Version: 0.0.94.8.

**Comment by BobStrogg** [comment]
This should be fixed in the latest release; it’ll attempt to preserve the selected date after a deletion...

**Comment by mitchcapper** [comment]
@fmonera  please re-open if not working for you in latest version.
