### ISSUE TITLE
Open Saved Clips Menu Error

### ISSUE THREAD

**Issue by gbgadgets** [BobStrogg/teslacam-browser#28]
TeslaCam Browswer 0.0.949
Ubuntu 18.04.2 LTS O/S

Click File > Open Saved Clips...
Then the error below is received.

![image](https://user-images.githubusercontent.com/321253/59307634-86efee00-8c64-11e9-858e-d0c0e8fc48b4.png)

**Comment by mitchcapper** [comment]
@gbgadgets can you confirm is this is still happening with the current version? #27 highlights some other path problems that might exist.

**Comment by mitchcapper** [comment]
Closing due to non-response please feel free to re-open if problem still exists.
