### ISSUE TITLE
Unable to start the application through index file or external file

### ISSUE THREAD

**Issue by umaimehm** [BobStrogg/teslacam-browser#31]
Hi, 
I followed the guide and opened up index.html in a browser. It showed a blank page.
I then opened external.html in a browser and it showed a page with many broken links and unstructured text.

How does one start the application ?
browsers: chrome, edge, IE

Can you please guide.
Thanks

**Comment by BobStrogg** [comment]
Hon- The easiest way to use the app is download an installer from the Releases page at https://github.com/BobStrogg/teslacam-browser/releases and run it.

For example, here’s a link to the latest Windows installer: https://github.com/BobStrogg/teslacam-browser/releases/download/v0.0.949/teslacam-browser-setup-0.0.949.exe

Hope this helps!

**Comment by BobStrogg** [comment]
It's now possible to run the app just with Node, which is great if you want to run it as a server on a Raspberry Pi:

`node server.js`

**Comment by mitchcapper** [comment]
@umaimehm please let us know if you are still having issues.
