### ISSUE TITLE
Video clips recorded since last firmware update will not play

### ISSUE THREAD

**Issue by pfakler** [BobStrogg/teslacam-browser#35]
Strange, but I just pulled my USB drive for the first time in a while, and all of the clips recorded after installing 2019.24.4 will not play. The app detects that there are files there for all three cameras and gives me the filenames, but I don't even get a thumbnail. These files play fine if I access them directly through finder and play with quicktime. All the earlier files on the USB drive played fine. I tried using another available web-based teslacam browser and had the same problem. Any ideas?

**Comment by BobStrogg** [comment]
Sounds a lot like this issue: https://github.com/BobStrogg/teslacam-browser/issues/34

Have you tried the "Browse" button in the app?  It'll open the UI in your default browser.  If that's Chrome or Firefox it'll probably have the same problem, but pasting the URL into Safari (or Edge on Windows) might serve as a workaround.

**Comment by pfakler** [comment]
Oops, sorry, should have read that one more carefully. Yup, does sound like the same issue. FWIW, I am not on HW3 (have 2.5). Will try that workaround. Hope there is a way to eventually make the app compatible with the new video file encoding. Thanks again.
