### ISSUE TITLE
hovering on the slider causes increase in video window size

### ISSUE THREAD

**Issue by JJeng** [BobStrogg/teslacam-browser#38]
Environment:
- TeslaCam Version 0.0.955
- Windows 10 Home 
- Windows Version 1809
- Browser Edge 44.17763.1.0 
- Tesla Model 3 Firmware 2019.24.4

Steps: 
1. Set default browser to Edge
2. Open TeslaCam Browser
3. If first time running choose TeslaCam source folder using Open Button
4. Click Browse to open TeslaCam in Edge
5. Select an event to playback in Edge
6. Attempt to use slider to advance through the video

Unexpected result: 
The video layout increases in size.

Impact on user: 
After some use of the slider the user is unable to see the videos as they have enlarged past the edge of the screen.

Reason for using Edge: 
Seems to allow videos from 2019.24.4 to play

**Comment by mitchcapper** [comment]
@JJeng Thanks for the detailed bug report mentioning #34 in here as well to link them even though we should make sure it probably works in Edge (then again they are killing it off for ChromeEdge).
