### ISSUE TITLE
Adjust Playback Speed

### ISSUE THREAD

**Issue by jball** [BobStrogg/teslacam-browser#5]
Provide a setting to increase the playback speed to quickly playback video.

**Comment by BobStrogg** [comment]
I'll look into it!  It's just using the HTML <video> tag, and looks like we can just set the 'playbackRate' property...

**Comment by jmtatsch** [comment]
Adjustable playback speed would be really awesome.
10x speed as in https://sentrycam.appspot.com is really saving a lot of time.
And maybe start playing automatically once an event is clicked.

**Comment by mitchcapper** [comment]
this seems to be in the latest release added on commit c39a5ec and could be closed

**Comment by BobStrogg** [comment]
Done
