### ISSUE TITLE
Feature request: remember last opened directory

### ISSUE THREAD

**Issue by senf42** [BobStrogg/teslacam-browser#6]
I view the same directory every time I run this. I can click open and then okay, but it would be nice if it loaded the last directory opened by default.

**Comment by BobStrogg** [comment]
Good idea.  Also, I think it's approaching the point it'll need a "Settings" page to remember some preferences (maybe configuration to launch 3rd party tools like tesla_dashcam).

**Comment by mitchcapper** [comment]
this is in the current version, and the  51820d7 commit seemed to fix if the directory went away as well. I would assume this could be closed now.

**Comment by mitchcapper** [comment]
@senf42 if this isn't still working for you let us know but I think it should work after that commit.
