### ISSUE TITLE
Blank Browser Window (Win10)

### ISSUE THREAD

**Issue by leonard4** [BobStrogg/teslacam-browser#9]
Getting a blank preview window, with no videos. I can click on each "area" and have it open the clip in explorer as well as view them from Explorer in Media Player. This is a HW3 Model 3 running Sentry mode and some manually saved clips.

![teslacambrowser](https://user-images.githubusercontent.com/1154391/57240360-1d385080-6fe3-11e9-86d5-caae6c90c034.png)

**Comment by BobStrogg** [comment]
Oh oh...  Does version 0.0.87 still work ok?

Chris

**Comment by leonard4** [comment]
I tried, v0.0.87, v0.0.83, and v0.0.7, and none of them work. So i'm thinking its unique to my system. Will keep playing with it and see what I can come up with.

Have any ideas on things to look at? :)

**Comment by BobStrogg** [comment]
That’s interesting.  The app is basically just a Chromium browser showing HTML video tags...  Is it possible there’s anything on your machine that somehow blocks videos in Chrome? (I’d be very surprised if it could affect a stand-alone app like this... but worth considering).

**Comment by BobStrogg** [comment]
Another possibility is some kind of file access / permission issue.

If you try “Toggle developer tools” on the “View” menu, then click the “Console” tab... are there any errors shown? (will be in red text probably... but any info could be useful).

**Comment by leonard4** [comment]
This is what i'm seeing with the console up:

![image](https://user-images.githubusercontent.com/1154391/57252915-43211d80-7002-11e9-9373-ee7f38b7859b.png)

**Comment by BobStrogg** [comment]
Hmmm...  I can certainly stop it throwing that first error, but not sure why it’s getting passed a “null” for the “folders” argument...

When you click “Open” in the app, does the folder select dialog appear more than once? (I’ve seen this happen; maybe clicking Cancel causes it to return null).

**Comment by BobStrogg** [comment]
In any case, the main issue seems to be the ERR_REQUEST_RANGE_NOT_SATISFIABLE error; is there anything unusual about the drive the files are on? (over a network share,

**Comment by leonard4** [comment]
No the open dialog only opens once. Not that I can think of, I do have some network shares but the Tesla videos are on a flash drive on my laptop.
